//import MenuBar from "@/components/MenuBar";
import type { Metadata } from "next";
import { Kanit} from "next/font/google";
import "./globals.css";

const kanit = Kanit({  
  subsets: ["thai"],
  weight: ["100", "200","300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.className}`}
      >
        {/* <MenuBar></MenuBar> */}
        {children}
        <div className="text-center font-bold text-gray-500 mt-20">
          <hr className="w-2xl mx-auto"/>
          Created by Sinlapachai Kaeobunrueang
          <br />
          Copyright &copy; 2024 All rights reserved.
        </div>
      </body>
    </html>
  );
}
// creat Layout in any folder in app to apply layout to all pages in that folder and subfolders